# Generated by Django 2.2 on 2019-12-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20191231_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-date']},
        ),
    ]
