# Generated by Django 2.2 on 2020-01-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_comments_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': []},
        ),
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
