# Generated by Django 2.2 on 2021-01-31 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20200105_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent_comment',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='feed.Comments'),
            preserve_default=False,
        ),
    ]
